apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api-deployment
  labels:
    app: notification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
        - name: notification-api
          image: bespinian/notification-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: MQ_URL
              value: amqp://notification-mq
            - name: DB_URL
              value: mongodb://notification-db:27017
          resources:
            limits:
              cpu: "100m"
